
interface _GlobalComponents {
      'Footer': typeof import("../components/footer.vue")['default']
    'GamesReview': typeof import("../components/games/review.vue")['default']
    'Loader': typeof import("../components/loader.vue")['default']
    'MPageCollectionItem': typeof import("../components/m-page/collection-item.vue")['default']
    'MPageCollection': typeof import("../components/m-page/collection.vue")['default']
    'MPageContactUs': typeof import("../components/m-page/contactUs.vue")['default']
    'MPageHeader': typeof import("../components/m-page/header.vue")['default']
    'MPageNewItem': typeof import("../components/m-page/new-item.vue")['default']
    'MPageUserItem': typeof import("../components/m-page/user-item.vue")['default']
    'Navbar': typeof import("../components/navbar.vue")['default']
    'NavbarProfile': typeof import("../components/navbar/profile.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'UIAccordion': typeof import("../components/ui/accordion/index")['Accordion']
    'UIAccordionContent': typeof import("../components/ui/accordion/index")['AccordionContent']
    'UIAccordionItem': typeof import("../components/ui/accordion/index")['AccordionItem']
    'UIAccordionTrigger': typeof import("../components/ui/accordion/index")['AccordionTrigger']
    'UIAvatar': typeof import("../components/ui/avatar/index")['Avatar']
    'UIAvatarImage': typeof import("../components/ui/avatar/index")['AvatarImage']
    'UIAvatarFallback': typeof import("../components/ui/avatar/index")['AvatarFallback']
    'UIButton': typeof import("../components/ui/button/index")['Button']
    'UICard': typeof import("../components/ui/card/index")['Card']
    'UICardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'UICardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'UICardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'UICardContent': typeof import("../components/ui/card/index")['CardContent']
    'UICardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'UICarousel': typeof import("../components/ui/carousel/index")['Carousel']
    'UICarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'UICarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'UICarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'UICarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'UICarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'UIDialog': typeof import("../components/ui/dialog/index")['Dialog']
    'UIDialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'UIDialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'UIDialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'UIDialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'UIDialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'UIDialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'UIDialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'UIDialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'UIDrawerPortal': typeof import("../components/ui/drawer/index")['DrawerPortal']
    'UIDrawerTrigger': typeof import("../components/ui/drawer/index")['DrawerTrigger']
    'UIDrawerClose': typeof import("../components/ui/drawer/index")['DrawerClose']
    'UIDrawer': typeof import("../components/ui/drawer/index")['Drawer']
    'UIDrawerOverlay': typeof import("../components/ui/drawer/index")['DrawerOverlay']
    'UIDrawerContent': typeof import("../components/ui/drawer/index")['DrawerContent']
    'UIDrawerHeader': typeof import("../components/ui/drawer/index")['DrawerHeader']
    'UIDrawerFooter': typeof import("../components/ui/drawer/index")['DrawerFooter']
    'UIDrawerTitle': typeof import("../components/ui/drawer/index")['DrawerTitle']
    'UIDrawerDescription': typeof import("../components/ui/drawer/index")['DrawerDescription']
    'UIDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'UIDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'UIDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'UIDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'UIDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'UIDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'UIDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'UIDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'UIDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'UIDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'UIDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'UIDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'UIDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'UIDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'UIDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'UIInput': typeof import("../components/ui/input/index")['Input']
    'UILabel': typeof import("../components/ui/label/index")['Label']
    'UISeparator': typeof import("../components/ui/separator/index")['Separator']
    'UISheet': typeof import("../components/ui/sheet/index")['Sheet']
    'UISheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'UISheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'UISheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'UISheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'UISheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'UISheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'UISheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'UIToaster': typeof import("../components/ui/toast/index")['Toaster']
    'UIToast': typeof import("../components/ui/toast/index")['Toast']
    'UIToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'UIToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'UIToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'UIToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'UIToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'UIToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyFooter': typeof import("../components/footer.vue")['default']
    'LazyGamesReview': typeof import("../components/games/review.vue")['default']
    'LazyLoader': typeof import("../components/loader.vue")['default']
    'LazyMPageCollectionItem': typeof import("../components/m-page/collection-item.vue")['default']
    'LazyMPageCollection': typeof import("../components/m-page/collection.vue")['default']
    'LazyMPageContactUs': typeof import("../components/m-page/contactUs.vue")['default']
    'LazyMPageHeader': typeof import("../components/m-page/header.vue")['default']
    'LazyMPageNewItem': typeof import("../components/m-page/new-item.vue")['default']
    'LazyMPageUserItem': typeof import("../components/m-page/user-item.vue")['default']
    'LazyNavbar': typeof import("../components/navbar.vue")['default']
    'LazyNavbarProfile': typeof import("../components/navbar/profile.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyUIAccordion': typeof import("../components/ui/accordion/index")['Accordion']
    'LazyUIAccordionContent': typeof import("../components/ui/accordion/index")['AccordionContent']
    'LazyUIAccordionItem': typeof import("../components/ui/accordion/index")['AccordionItem']
    'LazyUIAccordionTrigger': typeof import("../components/ui/accordion/index")['AccordionTrigger']
    'LazyUIAvatar': typeof import("../components/ui/avatar/index")['Avatar']
    'LazyUIAvatarImage': typeof import("../components/ui/avatar/index")['AvatarImage']
    'LazyUIAvatarFallback': typeof import("../components/ui/avatar/index")['AvatarFallback']
    'LazyUIButton': typeof import("../components/ui/button/index")['Button']
    'LazyUICard': typeof import("../components/ui/card/index")['Card']
    'LazyUICardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'LazyUICardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'LazyUICardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'LazyUICardContent': typeof import("../components/ui/card/index")['CardContent']
    'LazyUICardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'LazyUICarousel': typeof import("../components/ui/carousel/index")['Carousel']
    'LazyUICarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'LazyUICarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'LazyUICarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'LazyUICarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'LazyUICarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'LazyUIDialog': typeof import("../components/ui/dialog/index")['Dialog']
    'LazyUIDialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'LazyUIDialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'LazyUIDialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'LazyUIDialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'LazyUIDialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'LazyUIDialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'LazyUIDialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'LazyUIDialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'LazyUIDrawerPortal': typeof import("../components/ui/drawer/index")['DrawerPortal']
    'LazyUIDrawerTrigger': typeof import("../components/ui/drawer/index")['DrawerTrigger']
    'LazyUIDrawerClose': typeof import("../components/ui/drawer/index")['DrawerClose']
    'LazyUIDrawer': typeof import("../components/ui/drawer/index")['Drawer']
    'LazyUIDrawerOverlay': typeof import("../components/ui/drawer/index")['DrawerOverlay']
    'LazyUIDrawerContent': typeof import("../components/ui/drawer/index")['DrawerContent']
    'LazyUIDrawerHeader': typeof import("../components/ui/drawer/index")['DrawerHeader']
    'LazyUIDrawerFooter': typeof import("../components/ui/drawer/index")['DrawerFooter']
    'LazyUIDrawerTitle': typeof import("../components/ui/drawer/index")['DrawerTitle']
    'LazyUIDrawerDescription': typeof import("../components/ui/drawer/index")['DrawerDescription']
    'LazyUIDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'LazyUIDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'LazyUIDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'LazyUIDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'LazyUIDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'LazyUIDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'LazyUIDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'LazyUIDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'LazyUIDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'LazyUIDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'LazyUIDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'LazyUIDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'LazyUIDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'LazyUIDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'LazyUIDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'LazyUIInput': typeof import("../components/ui/input/index")['Input']
    'LazyUILabel': typeof import("../components/ui/label/index")['Label']
    'LazyUISeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazyUISheet': typeof import("../components/ui/sheet/index")['Sheet']
    'LazyUISheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'LazyUISheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'LazyUISheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'LazyUISheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'LazyUISheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'LazyUISheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'LazyUISheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'LazyUIToaster': typeof import("../components/ui/toast/index")['Toaster']
    'LazyUIToast': typeof import("../components/ui/toast/index")['Toast']
    'LazyUIToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'LazyUIToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'LazyUIToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'LazyUIToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'LazyUIToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'LazyUIToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Footer: typeof import("../components/footer.vue")['default']
export const GamesReview: typeof import("../components/games/review.vue")['default']
export const Loader: typeof import("../components/loader.vue")['default']
export const MPageCollectionItem: typeof import("../components/m-page/collection-item.vue")['default']
export const MPageCollection: typeof import("../components/m-page/collection.vue")['default']
export const MPageContactUs: typeof import("../components/m-page/contactUs.vue")['default']
export const MPageHeader: typeof import("../components/m-page/header.vue")['default']
export const MPageNewItem: typeof import("../components/m-page/new-item.vue")['default']
export const MPageUserItem: typeof import("../components/m-page/user-item.vue")['default']
export const Navbar: typeof import("../components/navbar.vue")['default']
export const NavbarProfile: typeof import("../components/navbar/profile.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const UIAccordion: typeof import("../components/ui/accordion/index")['Accordion']
export const UIAccordionContent: typeof import("../components/ui/accordion/index")['AccordionContent']
export const UIAccordionItem: typeof import("../components/ui/accordion/index")['AccordionItem']
export const UIAccordionTrigger: typeof import("../components/ui/accordion/index")['AccordionTrigger']
export const UIAvatar: typeof import("../components/ui/avatar/index")['Avatar']
export const UIAvatarImage: typeof import("../components/ui/avatar/index")['AvatarImage']
export const UIAvatarFallback: typeof import("../components/ui/avatar/index")['AvatarFallback']
export const UIButton: typeof import("../components/ui/button/index")['Button']
export const UICard: typeof import("../components/ui/card/index")['Card']
export const UICardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const UICardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const UICardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const UICardContent: typeof import("../components/ui/card/index")['CardContent']
export const UICardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const UICarousel: typeof import("../components/ui/carousel/index")['Carousel']
export const UICarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const UICarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const UICarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const UICarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const UICarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const UIDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const UIDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const UIDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const UIDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const UIDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const UIDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const UIDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const UIDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const UIDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const UIDrawerPortal: typeof import("../components/ui/drawer/index")['DrawerPortal']
export const UIDrawerTrigger: typeof import("../components/ui/drawer/index")['DrawerTrigger']
export const UIDrawerClose: typeof import("../components/ui/drawer/index")['DrawerClose']
export const UIDrawer: typeof import("../components/ui/drawer/index")['Drawer']
export const UIDrawerOverlay: typeof import("../components/ui/drawer/index")['DrawerOverlay']
export const UIDrawerContent: typeof import("../components/ui/drawer/index")['DrawerContent']
export const UIDrawerHeader: typeof import("../components/ui/drawer/index")['DrawerHeader']
export const UIDrawerFooter: typeof import("../components/ui/drawer/index")['DrawerFooter']
export const UIDrawerTitle: typeof import("../components/ui/drawer/index")['DrawerTitle']
export const UIDrawerDescription: typeof import("../components/ui/drawer/index")['DrawerDescription']
export const UIDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const UIDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const UIDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const UIDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const UIDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const UIDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const UIDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const UIDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const UIDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const UIDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const UIDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const UIDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const UIDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const UIDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const UIDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const UIInput: typeof import("../components/ui/input/index")['Input']
export const UILabel: typeof import("../components/ui/label/index")['Label']
export const UISeparator: typeof import("../components/ui/separator/index")['Separator']
export const UISheet: typeof import("../components/ui/sheet/index")['Sheet']
export const UISheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const UISheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const UISheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const UISheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const UISheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const UISheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const UISheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const UIToaster: typeof import("../components/ui/toast/index")['Toaster']
export const UIToast: typeof import("../components/ui/toast/index")['Toast']
export const UIToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const UIToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const UIToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const UIToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const UIToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const UIToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyFooter: typeof import("../components/footer.vue")['default']
export const LazyGamesReview: typeof import("../components/games/review.vue")['default']
export const LazyLoader: typeof import("../components/loader.vue")['default']
export const LazyMPageCollectionItem: typeof import("../components/m-page/collection-item.vue")['default']
export const LazyMPageCollection: typeof import("../components/m-page/collection.vue")['default']
export const LazyMPageContactUs: typeof import("../components/m-page/contactUs.vue")['default']
export const LazyMPageHeader: typeof import("../components/m-page/header.vue")['default']
export const LazyMPageNewItem: typeof import("../components/m-page/new-item.vue")['default']
export const LazyMPageUserItem: typeof import("../components/m-page/user-item.vue")['default']
export const LazyNavbar: typeof import("../components/navbar.vue")['default']
export const LazyNavbarProfile: typeof import("../components/navbar/profile.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyUIAccordion: typeof import("../components/ui/accordion/index")['Accordion']
export const LazyUIAccordionContent: typeof import("../components/ui/accordion/index")['AccordionContent']
export const LazyUIAccordionItem: typeof import("../components/ui/accordion/index")['AccordionItem']
export const LazyUIAccordionTrigger: typeof import("../components/ui/accordion/index")['AccordionTrigger']
export const LazyUIAvatar: typeof import("../components/ui/avatar/index")['Avatar']
export const LazyUIAvatarImage: typeof import("../components/ui/avatar/index")['AvatarImage']
export const LazyUIAvatarFallback: typeof import("../components/ui/avatar/index")['AvatarFallback']
export const LazyUIButton: typeof import("../components/ui/button/index")['Button']
export const LazyUICard: typeof import("../components/ui/card/index")['Card']
export const LazyUICardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const LazyUICardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const LazyUICardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const LazyUICardContent: typeof import("../components/ui/card/index")['CardContent']
export const LazyUICardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const LazyUICarousel: typeof import("../components/ui/carousel/index")['Carousel']
export const LazyUICarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const LazyUICarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const LazyUICarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const LazyUICarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const LazyUICarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const LazyUIDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const LazyUIDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const LazyUIDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const LazyUIDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const LazyUIDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const LazyUIDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const LazyUIDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const LazyUIDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const LazyUIDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const LazyUIDrawerPortal: typeof import("../components/ui/drawer/index")['DrawerPortal']
export const LazyUIDrawerTrigger: typeof import("../components/ui/drawer/index")['DrawerTrigger']
export const LazyUIDrawerClose: typeof import("../components/ui/drawer/index")['DrawerClose']
export const LazyUIDrawer: typeof import("../components/ui/drawer/index")['Drawer']
export const LazyUIDrawerOverlay: typeof import("../components/ui/drawer/index")['DrawerOverlay']
export const LazyUIDrawerContent: typeof import("../components/ui/drawer/index")['DrawerContent']
export const LazyUIDrawerHeader: typeof import("../components/ui/drawer/index")['DrawerHeader']
export const LazyUIDrawerFooter: typeof import("../components/ui/drawer/index")['DrawerFooter']
export const LazyUIDrawerTitle: typeof import("../components/ui/drawer/index")['DrawerTitle']
export const LazyUIDrawerDescription: typeof import("../components/ui/drawer/index")['DrawerDescription']
export const LazyUIDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const LazyUIDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const LazyUIDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const LazyUIDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const LazyUIDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const LazyUIDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const LazyUIDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const LazyUIDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const LazyUIDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const LazyUIDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const LazyUIDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const LazyUIDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const LazyUIDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const LazyUIDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const LazyUIDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const LazyUIInput: typeof import("../components/ui/input/index")['Input']
export const LazyUILabel: typeof import("../components/ui/label/index")['Label']
export const LazyUISeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazyUISheet: typeof import("../components/ui/sheet/index")['Sheet']
export const LazyUISheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const LazyUISheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const LazyUISheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const LazyUISheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const LazyUISheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const LazyUISheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const LazyUISheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const LazyUIToaster: typeof import("../components/ui/toast/index")['Toaster']
export const LazyUIToast: typeof import("../components/ui/toast/index")['Toast']
export const LazyUIToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const LazyUIToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const LazyUIToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const LazyUIToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const LazyUIToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const LazyUIToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
