
interface _GlobalComponents {
      'MPageCollectionItem': typeof import("../components/m-page/collection-item.vue")['default']
    'MPageCollection': typeof import("../components/m-page/collection.vue")['default']
    'MPageHeader': typeof import("../components/m-page/header.vue")['default']
    'MPageNewItem': typeof import("../components/m-page/new-item.vue")['default']
    'Navbar': typeof import("../components/navbar.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'UIButton': typeof import("../components/ui/button/index")['Button']
    'UICard': typeof import("../components/ui/card/index")['Card']
    'UICardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'UICardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'UICardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'UICardContent': typeof import("../components/ui/card/index")['CardContent']
    'UICardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'UICarousel': typeof import("../components/ui/carousel/index")['Carousel']
    'UICarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'UICarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'UICarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'UICarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'UICarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'UIDrawerPortal': typeof import("../components/ui/drawer/index")['DrawerPortal']
    'UIDrawerTrigger': typeof import("../components/ui/drawer/index")['DrawerTrigger']
    'UIDrawerClose': typeof import("../components/ui/drawer/index")['DrawerClose']
    'UIDrawer': typeof import("../components/ui/drawer/index")['Drawer']
    'UIDrawerOverlay': typeof import("../components/ui/drawer/index")['DrawerOverlay']
    'UIDrawerContent': typeof import("../components/ui/drawer/index")['DrawerContent']
    'UIDrawerHeader': typeof import("../components/ui/drawer/index")['DrawerHeader']
    'UIDrawerFooter': typeof import("../components/ui/drawer/index")['DrawerFooter']
    'UIDrawerTitle': typeof import("../components/ui/drawer/index")['DrawerTitle']
    'UIDrawerDescription': typeof import("../components/ui/drawer/index")['DrawerDescription']
    'UIForm': typeof import("../components/ui/form/index")['Form']
    'UIFormField': typeof import("../components/ui/form/index")['FormField']
    'UIFormItem': typeof import("../components/ui/form/index")['FormItem']
    'UIFormLabel': typeof import("../components/ui/form/index")['FormLabel']
    'UIFormControl': typeof import("../components/ui/form/index")['FormControl']
    'UIFormMessage': typeof import("../components/ui/form/index")['FormMessage']
    'UIFormDescription': typeof import("../components/ui/form/index")['FormDescription']
    'UIInput': typeof import("../components/ui/input/index")['Input']
    'UILabel': typeof import("../components/ui/label/index")['Label']
    'UISeparator': typeof import("../components/ui/separator/index")['Separator']
    'UISheet': typeof import("../components/ui/sheet/index")['Sheet']
    'UISheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'UISheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'UISheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'UISheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'UISheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'UISheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'UISheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'UIToaster': typeof import("../components/ui/toast/index")['Toaster']
    'UIToast': typeof import("../components/ui/toast/index")['Toast']
    'UIToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'UIToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'UIToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'UIToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'UIToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'UIToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyMPageCollectionItem': typeof import("../components/m-page/collection-item.vue")['default']
    'LazyMPageCollection': typeof import("../components/m-page/collection.vue")['default']
    'LazyMPageHeader': typeof import("../components/m-page/header.vue")['default']
    'LazyMPageNewItem': typeof import("../components/m-page/new-item.vue")['default']
    'LazyNavbar': typeof import("../components/navbar.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyUIButton': typeof import("../components/ui/button/index")['Button']
    'LazyUICard': typeof import("../components/ui/card/index")['Card']
    'LazyUICardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'LazyUICardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'LazyUICardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'LazyUICardContent': typeof import("../components/ui/card/index")['CardContent']
    'LazyUICardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'LazyUICarousel': typeof import("../components/ui/carousel/index")['Carousel']
    'LazyUICarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'LazyUICarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'LazyUICarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'LazyUICarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'LazyUICarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'LazyUIDrawerPortal': typeof import("../components/ui/drawer/index")['DrawerPortal']
    'LazyUIDrawerTrigger': typeof import("../components/ui/drawer/index")['DrawerTrigger']
    'LazyUIDrawerClose': typeof import("../components/ui/drawer/index")['DrawerClose']
    'LazyUIDrawer': typeof import("../components/ui/drawer/index")['Drawer']
    'LazyUIDrawerOverlay': typeof import("../components/ui/drawer/index")['DrawerOverlay']
    'LazyUIDrawerContent': typeof import("../components/ui/drawer/index")['DrawerContent']
    'LazyUIDrawerHeader': typeof import("../components/ui/drawer/index")['DrawerHeader']
    'LazyUIDrawerFooter': typeof import("../components/ui/drawer/index")['DrawerFooter']
    'LazyUIDrawerTitle': typeof import("../components/ui/drawer/index")['DrawerTitle']
    'LazyUIDrawerDescription': typeof import("../components/ui/drawer/index")['DrawerDescription']
    'LazyUIForm': typeof import("../components/ui/form/index")['Form']
    'LazyUIFormField': typeof import("../components/ui/form/index")['FormField']
    'LazyUIFormItem': typeof import("../components/ui/form/index")['FormItem']
    'LazyUIFormLabel': typeof import("../components/ui/form/index")['FormLabel']
    'LazyUIFormControl': typeof import("../components/ui/form/index")['FormControl']
    'LazyUIFormMessage': typeof import("../components/ui/form/index")['FormMessage']
    'LazyUIFormDescription': typeof import("../components/ui/form/index")['FormDescription']
    'LazyUIInput': typeof import("../components/ui/input/index")['Input']
    'LazyUILabel': typeof import("../components/ui/label/index")['Label']
    'LazyUISeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazyUISheet': typeof import("../components/ui/sheet/index")['Sheet']
    'LazyUISheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'LazyUISheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'LazyUISheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'LazyUISheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'LazyUISheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'LazyUISheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'LazyUISheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'LazyUIToaster': typeof import("../components/ui/toast/index")['Toaster']
    'LazyUIToast': typeof import("../components/ui/toast/index")['Toast']
    'LazyUIToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'LazyUIToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'LazyUIToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'LazyUIToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'LazyUIToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'LazyUIToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const MPageCollectionItem: typeof import("../components/m-page/collection-item.vue")['default']
export const MPageCollection: typeof import("../components/m-page/collection.vue")['default']
export const MPageHeader: typeof import("../components/m-page/header.vue")['default']
export const MPageNewItem: typeof import("../components/m-page/new-item.vue")['default']
export const Navbar: typeof import("../components/navbar.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const UIButton: typeof import("../components/ui/button/index")['Button']
export const UICard: typeof import("../components/ui/card/index")['Card']
export const UICardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const UICardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const UICardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const UICardContent: typeof import("../components/ui/card/index")['CardContent']
export const UICardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const UICarousel: typeof import("../components/ui/carousel/index")['Carousel']
export const UICarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const UICarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const UICarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const UICarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const UICarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const UIDrawerPortal: typeof import("../components/ui/drawer/index")['DrawerPortal']
export const UIDrawerTrigger: typeof import("../components/ui/drawer/index")['DrawerTrigger']
export const UIDrawerClose: typeof import("../components/ui/drawer/index")['DrawerClose']
export const UIDrawer: typeof import("../components/ui/drawer/index")['Drawer']
export const UIDrawerOverlay: typeof import("../components/ui/drawer/index")['DrawerOverlay']
export const UIDrawerContent: typeof import("../components/ui/drawer/index")['DrawerContent']
export const UIDrawerHeader: typeof import("../components/ui/drawer/index")['DrawerHeader']
export const UIDrawerFooter: typeof import("../components/ui/drawer/index")['DrawerFooter']
export const UIDrawerTitle: typeof import("../components/ui/drawer/index")['DrawerTitle']
export const UIDrawerDescription: typeof import("../components/ui/drawer/index")['DrawerDescription']
export const UIForm: typeof import("../components/ui/form/index")['Form']
export const UIFormField: typeof import("../components/ui/form/index")['FormField']
export const UIFormItem: typeof import("../components/ui/form/index")['FormItem']
export const UIFormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const UIFormControl: typeof import("../components/ui/form/index")['FormControl']
export const UIFormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const UIFormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const UIInput: typeof import("../components/ui/input/index")['Input']
export const UILabel: typeof import("../components/ui/label/index")['Label']
export const UISeparator: typeof import("../components/ui/separator/index")['Separator']
export const UISheet: typeof import("../components/ui/sheet/index")['Sheet']
export const UISheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const UISheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const UISheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const UISheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const UISheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const UISheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const UISheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const UIToaster: typeof import("../components/ui/toast/index")['Toaster']
export const UIToast: typeof import("../components/ui/toast/index")['Toast']
export const UIToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const UIToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const UIToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const UIToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const UIToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const UIToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyMPageCollectionItem: typeof import("../components/m-page/collection-item.vue")['default']
export const LazyMPageCollection: typeof import("../components/m-page/collection.vue")['default']
export const LazyMPageHeader: typeof import("../components/m-page/header.vue")['default']
export const LazyMPageNewItem: typeof import("../components/m-page/new-item.vue")['default']
export const LazyNavbar: typeof import("../components/navbar.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyUIButton: typeof import("../components/ui/button/index")['Button']
export const LazyUICard: typeof import("../components/ui/card/index")['Card']
export const LazyUICardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const LazyUICardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const LazyUICardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const LazyUICardContent: typeof import("../components/ui/card/index")['CardContent']
export const LazyUICardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const LazyUICarousel: typeof import("../components/ui/carousel/index")['Carousel']
export const LazyUICarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const LazyUICarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const LazyUICarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const LazyUICarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const LazyUICarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const LazyUIDrawerPortal: typeof import("../components/ui/drawer/index")['DrawerPortal']
export const LazyUIDrawerTrigger: typeof import("../components/ui/drawer/index")['DrawerTrigger']
export const LazyUIDrawerClose: typeof import("../components/ui/drawer/index")['DrawerClose']
export const LazyUIDrawer: typeof import("../components/ui/drawer/index")['Drawer']
export const LazyUIDrawerOverlay: typeof import("../components/ui/drawer/index")['DrawerOverlay']
export const LazyUIDrawerContent: typeof import("../components/ui/drawer/index")['DrawerContent']
export const LazyUIDrawerHeader: typeof import("../components/ui/drawer/index")['DrawerHeader']
export const LazyUIDrawerFooter: typeof import("../components/ui/drawer/index")['DrawerFooter']
export const LazyUIDrawerTitle: typeof import("../components/ui/drawer/index")['DrawerTitle']
export const LazyUIDrawerDescription: typeof import("../components/ui/drawer/index")['DrawerDescription']
export const LazyUIForm: typeof import("../components/ui/form/index")['Form']
export const LazyUIFormField: typeof import("../components/ui/form/index")['FormField']
export const LazyUIFormItem: typeof import("../components/ui/form/index")['FormItem']
export const LazyUIFormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const LazyUIFormControl: typeof import("../components/ui/form/index")['FormControl']
export const LazyUIFormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const LazyUIFormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const LazyUIInput: typeof import("../components/ui/input/index")['Input']
export const LazyUILabel: typeof import("../components/ui/label/index")['Label']
export const LazyUISeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazyUISheet: typeof import("../components/ui/sheet/index")['Sheet']
export const LazyUISheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const LazyUISheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const LazyUISheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const LazyUISheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const LazyUISheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const LazyUISheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const LazyUISheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const LazyUIToaster: typeof import("../components/ui/toast/index")['Toaster']
export const LazyUIToast: typeof import("../components/ui/toast/index")['Toast']
export const LazyUIToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const LazyUIToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const LazyUIToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const LazyUIToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const LazyUIToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const LazyUIToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
