// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03.06.2024, 08:37:26
const configMerger = require("F:/Projects/PlayHub/playhub/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["F:/Projects/PlayHub/playhub/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/PlayHub/playhub/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/PlayHub/playhub/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/PlayHub/playhub/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/PlayHub/playhub/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/PlayHub/playhub/plugins/**/*.{js,ts,mjs}","F:/Projects/PlayHub/playhub/composables/**/*.{js,ts,mjs}","F:/Projects/PlayHub/playhub/utils/**/*.{js,ts,mjs}","F:/Projects/PlayHub/playhub/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/PlayHub/playhub/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/PlayHub/playhub/app.config.{js,ts,mjs}"] }));

module.exports = config
